modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/Liquid-XP/issues"

[[mods]]
modId="liquidxp"
displayName="Liquid XP"
version="${file.jarVersion}"
authors="Ewy"
credits="Placeholder text"
description="Store XP as a liquid"

[[dependencies.liquidxp]]
modId="bibliotheca"
mandatory=true
versionRange="[1.5.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.liquidxp]]
modId="forge"
mandatory=true
versionRange="[33.0.+,)"
ordering="AFTER"
side="BOTH"

[[dependencies.liquidxp]]
modId="minecraft"
mandatory=true
versionRange="[1.16.+,]"
ordering="NONE"
side="BOTH"